name: 'Jira Release Notes'
description: 'Automatic release note generated based on jira tickets in commits'
author: 'Luis Morales'
inputs:
  jiraHost: # change this
    required: true
    description: 'url of jira server'
  jiraCode: # change this
    required: true
    description: 'jira project code'
  jiraUsername: # change this
    required: true
    description: 'jira username'
  jiraPassword: # change this
    required: true
    description: 'jira username password'
runs:
  using: 'node16'
  main: 'dist/index.js'
